#BrowserName=chrome
#BrowserName=Safari
BrowserName=Edge


#ApplicationURL=https://mail.rediff.com/cgi-bin/login.cgi
ApplicationURL=https://www.automationexercise.com/


username=standard_user
password=secret_sauce