#Object repository
#WebElement locator

#Login page

login_rediffmailid_id=login1
login_password_name=passwd
login_loginbttn_css=[class='signin-btn']


#Registartion Page

login_newuser_getnewrediffmailid_xpath=//a[text()='Get a new Rediffmail ID']
register_fullname_css=[placeholder='Enter your full name']
register_emailid_xpath=//input[contains(@name,'login')]
register_dob_day_css=[class='day']
register_gender_female_xpath=//label[text()='Female']



#Project 1: Automation excercise

home_menu_products_xpath=//a[text()=' Products']
product_search_textbox_id=search_product
product_search_button_id=submit_search